import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'tr' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, any> = {
  tr: {
    header: {
      home: 'Ana Sayfa',
      tours: 'Turlar',
      destinations: 'Destinasyonlar',
      visa: 'Vize Desteği',
      blog: 'Blog',
      about: 'Hakkımızda',
      contact: 'İletişim',
      bookNow: 'Hemen Rezervasyon',
      announcement: 'Erken Rezervasyon Fırsatlarında Son Gün Bugün!',
      checkOffers: 'Fırsatları İncele →',
      lastMinuteDeals: '🎉 Son Dakika Kampanyaları',
      viewDeals: 'Fırsatları İncele',
      hours: 'Saat',
      minutes: 'Dakika',
      seconds: 'Saniye',
      search: 'Ara',
      searchPlaceholder: 'Dubai, Bali, Tayland...'
    },
    hero: {
      title: 'Bir Sonraki Maceranızı Keşfedin',
      subtitle: 'Özenle seçilmiş tur paketlerimiz ve uzman rehberlerimizle dünyanın muhteşem destinasyonlarını keşfedin',
      destination: 'Destinasyon',
      destinationPlaceholder: 'Nereye?',
      date: 'Tarih',
      guests: 'Misafir Sayısı',
      guest: 'Misafir',
      search: 'Ara',
      explorePackages: 'Paketleri Keşfet',
      contactUs: 'Bize Ulaşın'
    },
    home: {
      popularDestinations: 'Popüler Destinasyonlar',
      popularDestinationsSubtitle: 'En çok tercih edilen tatil noktalarını keşfedin',
      featuredPackages: 'Öne Çıkan Paketler',
      featuredPackagesSubtitle: 'Size özel hazırlanmış tur paketlerimizi inceleyin',
      whyChooseUs: 'Neden Bizi Seçmelisiniz?',
      whyChooseUsSubtitle: '17 yıllık tecrübemiz ve profesyonel hizmet anlayışımızla yanınızdayız',
      bestPrices: 'En İyi Fiyatlar',
      bestPricesDesc: 'Piyasadaki en rekabetçi fiyatlarla kaliteli tatil deneyimi',
      expertGuides: 'Uzman Rehberler',
      expertGuidesDesc: 'Deneyimli ve yerel rehberlerimizle unutulmaz geziler',
      support247: '7/24 Destek',
      support247Desc: 'Her zaman yanınızdayız, sorunlarınıza anında çözüm',
      easyBooking: 'Kolay Rezervasyon',
      easyBookingDesc: 'Sadece birkaç tıklama ile hayalinizdeki tatili rezerve edin',
      from: 'dan itibaren',
      viewAllTours: 'Tüm Turları İncele',
      rating: 'Puan',
      reviews: 'Yorum',
      days: 'Gün',
      groupSize: 'Grup Büyüklüğü',
      people: 'kişi',
      departure: 'Hareket',
      everyday: 'Her gün',
      monThu: 'Pzt, Per',
      tueWedSat: 'Salı, Çarşamba, Cumartesi',
      worldwideCoverage: 'Dünya Çapında Kapsama',
      worldwideCoverageDesc: '6 kıtada 500+ destinasyon keşfedin',
      safeSecure: 'Güvenli & Emniyetli',
      safeSecureDesc: '7/24 destek ile güvenliğiniz önceliğimiz',
      support247Title: '7/24 Destek',
      support247TitleDesc: 'Özel ekibimizle her zaman, her yerde yardım alın',
      bestPricesTitle: 'En İyi Fiyatlar',
      bestPricesTitleDesc: 'Gizli ücret olmayan rekabetçi fiyatlandırma'
    },
    tours: {
      international: 'Yurt Dışı Turları',
      abroad: 'Yurtdışı Turları',
      culture: 'Kültür Turları',
      turkey: 'Türkiye Turları',
      visaFree: 'Vizesiz Yurt Dışı',
      montenegro: 'Karadağ',
      balkans: 'Balkan Turları',
      italy: 'İtalya',
      dubai: 'Dubai',
      japan: 'Japonya',
      egypt: 'Mısır',
      thailand: 'Tayland',
      bali: 'Bali (Endonezya)',
      greece: 'Yunanistan',
      europeCulture: 'Avrupa Kültür Turları',
      asiaCulture: 'Asya Kültür Turları',
      middleEast: 'Orta Doğu Turları',
      holyLands: 'Kutsal Topraklar',
      farEast: 'Uzak Doğu',
      antalya: 'Antalya Turları',
      cappadocia: 'Kapadokya Turları',
      aegean: 'Ege Turları',
      mediterranean: 'Akdeniz Turları'
    },
    destinations: {
      title: 'Popüler Destinasyonlar',
      subtitle: 'En çok tercih edilen tatil noktalarını keşfedin',
      tours: 'Tur'
    },
    packages: {
      title: 'Öne Çıkan Paketler',
      subtitle: 'Size özel hazırlanmış tur paketlerimizi inceleyin',
      viewAll: 'Tüm Turları İncele',
      from: 'dan itibaren',
      perPerson: 'kişi başı',
      viewDetails: 'Detayları İncele',
      days: 'Gün'
    },
    features: {
      title: 'Neden Bizi Seçmelisiniz?',
      bestPrices: 'En İyi Fiyatlar',
      bestPricesDesc: 'Piyasadaki en rekabetçi fiyatlarla kaliteli tatil deneyimi',
      expertGuides: 'Uzman Rehberler',
      expertGuidesDesc: 'Deneyimli ve yerel rehberlerimizle unutulmaz geziler',
      support: '7/24 Destek',
      supportDesc: 'Her zaman yanınızdayız, sorunlarınıza anında çözüm'
    },
    footer: {
      tagline: 'Dünya çapında unutulmaz seyahat deneyimleri için güvenilir partneriniz.',
      quickLinks: 'Hızlı Bağlantılar',
      aboutUs: 'Hakkımızda',
      destinations: 'Destinasyonlar',
      tourPackages: 'Tur Paketleri',
      visaSupport: 'Vize Desteği',
      contact: 'İletişim',
      services: 'Hizmetlerimiz',
      hotelReservation: 'Otel Rezervasyonu',
      flightTicket: 'Uçak Bileti',
      tourGuides: 'Tur Rehberleri',
      travelInsurance: 'Seyahat Sigortası',
      copyright: 'Tüm hakları saklıdır.'
    },
    visa: {
      title: 'Vize Destek Hizmetleri',
      subtitle: 'Vize sürecinizde yanınızdayız',
      description: 'Profesyonel ekibimizle vize başvuru sürecinizi kolaylaştırıyoruz.',
      visaConsultancy: 'Vize Danışmanlığı',
      all: 'Vize Danışmanlığı',
      dubai: 'Dubai Vize',
      subtitle2: 'Yurtdışı vize başvurularınız hakkında bilgiler. Vize işlemlerinizi profesyonel ekibimizle kolaylaştırın.',
      applyNow: 'Hemen Başvur',
      ourServices: 'Hizmetlerimiz',
      whyChooseUs: 'Neden Bizi Tercih Etmelisiniz?',
      documentPreparation: 'Belge Hazırlama',
      documentPreparationDesc: 'Tüm vize başvuru belgelerinizi sizin için hazırlıyoruz. Eksik evrak konusunda destek sağlıyoruz.',
      fastProcess: 'Hızlı İşlem',
      fastProcessDesc: 'Vize başvurularınızı en hızlı şekilde tamamlıyor ve takip ediyoruz.',
      approvalGuarantee: 'Onay Garantisi',
      approvalGuaranteeDesc: 'Yüksek onay oranı ile profesyonel vize danışmanlığı hizmeti sunuyoruz.',
      allCountries: 'Tüm Ülkeler',
      allCountriesDesc: 'Dünyanın her ülkesi için vize başvuru desteği sağlıyoruz.',
      secureProcess: 'Güvenli Süreç',
      secureProcessDesc: 'Belgeleriniz güvenli bir şekilde işlenir ve gizliliğiniz korunur.',
      expertTeam: 'Uzman Ekip',
      expertTeamDesc: 'Deneyimli vize danışmanlarımız her adımda yanınızda.',
      passportServices: 'Pasaport Hizmetleri',
      passportTitle: 'Pasaport Çıkarmak',
      passportDesc: 'Pasaport başvurusunun yaş ayrımı gözetilmeksizin şahsen yapılması gerekmektedir. 2 Nisan 2018 tarihinden itibaren pasaport başvurusu Nüfus Müdürlüklerine yapılmaktadır.',
      passportDesc2: 'Pasaport ücreti internetten veya bankalara yatırıp, yine internetten veya telefonla pasaport randevusu aldıktan sonra, nüfus müdürlüklerine 2 adet biyometrik fotoğraf ve TC Kimlik Kartınızla gitmeniz yeterlidir.',
      passportRequirements: 'Pasaport İçin Gerekli Evraklar',
      requirement1: 'Biyometrik 2 adet fotoğrafınız',
      requirement2: 'TC Kimlik Kartı veya nüfus cüzdanınız',
      requirement3: 'Varsa eski pasaportunuz',
      requirement4: 'Öğrenci belgesi (Harçsız pasaport talep edenler için)',
      requirement5: 'Ergin olmayanlar veya kısıtlılar için muvafakat belgesi',
      simplifyProcess: 'Vize Sürecinizi Bizimle Kolaylaştırın',
      processDesc: 'GNC Travel Vize Danışmanlık ile profesyonel ve kaliteli vize danışmanlık servisini alarak eksiksiz bir başvuru yapıp, vize reddi riskini minimize edebilirsiniz.',
      contactInfo: 'Ülkelere göre vize bilgilenmesi almak ve detaylı vize başvuru sürecinizi öğrenmek için +90 543 220 05 43 numarasını arayın ya da info@gnctravel.com adresine e-posta gönderin.',
      getFreeConsultation: 'Ücretsiz Danışmanlık Alın',
      visaApplicationForm: 'Vize Başvuru Formu',
      formDesc: 'Formu doldurun, uzman ekibimiz en kısa sürede sizinle iletişime geçsin.',
      fullName: 'Ad Soyad',
      fullNamePlaceholder: 'Adınız ve soyadınız',
      emailPlaceholder: 'ornek@email.com',
      phone: 'Telefon',
      phonePlaceholder: '+90 5XX XXX XX XX',
      destinationCountry: 'Gitmek İstediğiniz Ülke',
      destinationCountryPlaceholder: 'Örn: Amerika Birleşik Devletleri',
      passportStatus: 'Pasaport Durumu',
      passportStatusPlaceholder: 'Seçiniz',
      havePassport: 'Pasaportum Var',
      noPassport: 'Pasaportum Yok',
      expiredPassport: 'Pasaportum Var Ama Süresi Dolmuş',
      yourMessage: 'Mesajınız',
      messagePlaceholder: 'Vize başvurunuz hakkında bilgi vermek isterseniz...',
      submitApplication: 'Başvuruyu Gönder',
      submitSuccess: 'Başvurunuz alındı! En kısa sürede size dönüş yapacağız.',
      manyApplications: 'Ülkemizde Pek Çok Vize Başvurusu',
      applicationsDesc: 'Ülkemizde pek çok vize başvurusu, yanlış ya da eksik doldurulmuş formlar, uygun olmayan belge sunumu, belgelerin gerektiği şekilde çevrilmemesi gibi nedenlerle geri çevrilmektedir.',
      professionalService: 'Profesyonel Vize Danışmanlığı',
      visaBlog: 'Vize Rehberi & Blog',
      blogDesc: 'Vize başvuru süreçleri hakkında detaylı bilgiler, gerekli belgeler ve uzman ipuçları',
      touristVisa: 'Turist Vizesi Nasıl Alınır?',
      touristVisaDesc: 'Yurtdışına turistik seyahat için gerekli belgeler, başvuru süreci ve dikkat edilmesi gereken noktalar.',
      readMore: 'Devamını Oku',
      studentVisa: 'Öğrenci Vizesi Başvurusu',
      studentVisaDesc: 'Yurtdışında eğitim görmek için öğrenci vizesi başvuru süreci, gerekli belgeler ve önemli detaylar.',
      workVisa: 'İş Vizesi Başvuru Rehberi',
      workVisaDesc: 'Yurtdışında çalışmak için iş vizesi başvurusu, işveren sponsorluğu ve gerekli evraklar.',
      viewAllBlogPosts: 'Tüm Blog Yazılarını Görüntüle',
      processInfo: 'Yurtdışı vize başvuru işlemlerinizi başvurudan ülkeye göre birçok farklılık göstermektedir. Profesyonel ekibimizle size en uygun çözümü sunuyoruz.',
      dubaiVisa: {
        title: 'Dubai Visa Services',
        subtitle: 'We simplify your visa process for Dubai travel',
        heroDesc: 'Professional visa consultancy service for your travel to the United Arab Emirates',
        whyDubai: 'Why Dubai?',
        whyDubaiDesc: 'Dubai is one of the world\'s most popular tourist destinations with luxury shopping malls, modern architecture, vibrant nightlife and family-friendly entertainment centers.',
        visaTypes: 'Dubai Visa Types',
        touristVisa: 'Tourist Visa',
        touristVisaDesc: 'Discover all the beauty of Dubai with a 30 or 90-day tourist visa',
        transitVisa: 'Transit Visa',
        transitVisaDesc: 'Transit visa for stays up to 96 hours in Dubai',
        multipleEntry: 'Multiple Entry Visa',
        multipleEntryDesc: 'Visa that allows multiple entries within 90 days',
        requirements: 'Required Documents',
        requirement1: 'Passport valid for at least 6 months',
        requirement2: 'Passport-size color photograph',
        requirement3: 'Hotel reservation document',
        requirement4: 'Flight ticket reservation',
        requirement5: 'Health insurance',
        requirement6: 'Bank statement',
        processTitle: 'Visa Application Process',
        processStep1: '1. Application Form',
        processStep1Desc: 'Fill out your online form',
        processStep2: '2. Document Check',
        processStep2Desc: 'Let us check your documents',
        processStep3: '3. Application',
        processStep3Desc: 'We make your application',
        processStep4: '4. Approval',
        processStep4Desc: 'Receive your visa',
        pricing: 'Pricing',
        from: 'from',
        applyNow: 'Apply Now',
        recommendedTours: 'Recommended Dubai Tours',
        viewAllDubaiTours: 'View All Dubai Tours',
        faq: 'Frequently Asked Questions',
        faqQ1: 'How long does it take to get a Dubai visa?',
        faqA1: 'Usually the visa approval is received within 3-5 business days.',
        faqQ2: 'How much does a Dubai visa cost?',
        faqA2: 'Visa fees vary depending on the visa type. Please contact us for detailed information.',
        faqQ3: 'How long does the Dubai visa process take?',
        faqA3: 'We recommend you allow an average of 1 week for the application process to be completed.',
        faqQ4: 'How long must my passport be valid for a Dubai visa?',
        faqA4: 'Your passport must be valid for at least 6 months.',
        contactForVisa: 'Contact Us for Visa Consultancy',
        contactDesc: 'Our expert team is ready to help you with your Dubai visa process'
      }
    },
    about: {
      title: 'Hakkımızda',
      subtitle: '17 yıllık tecrübemizle yanınızdayız'
    },
    contact: {
      title: 'İletişim',
      subtitle: 'Size nasıl yardımcı olabiliriz?',
      getInTouch: 'Bizimle İletişime Geçin',
      getInTouchDesc: 'Sorularınız, önerileriniz veya destek talepleriniz için bize ulaşın. Ekibimiz size yardımcı olmak için burada.',
      address: 'Adresimiz',
      addressText: 'Side Mah. Yavuz Sultan Selim Blv. No:6 A-Z01 MANAVGAT / ANTALYA',
      phone: 'Telefon',
      email: 'E-posta',
      workingHours: 'Çalışma Saatlerimiz',
      workingHoursText: 'Pazartesi – Cumartesi : 09:00 – 19:00',
      sundayClosed: 'Pazar günleri kapalıyız',
      sendMessage: 'Mesaj Gönderin',
      name: 'Adınız',
      namePlaceholder: 'Adınızı girin',
      emailPlaceholder: 'E-posta adresiniz',
      phonePlaceholder: 'Telefon numaranız',
      subject: 'Konu',
      subjectPlaceholder: 'Konuyu seçin',
      general: 'Genel Bilgi',
      tourInquiry: 'Tur Bilgisi',
      visaSupport: 'Vize Desteği',
      complaint: 'Şikayet/Öneri',
      message: 'Mesajınız',
      messagePlaceholder: 'Mesajınızı buraya yazın...',
      send: 'Mesajı Gönder',
      sending: 'Gönderiliyor...',
      successMessage: 'Teşekkürler! Mesajınız alındı. En kısa sürede size dönüş yapacağız.',
      mapTitle: 'Konumumuz',
      whyContact: 'Neden Bize Ulaşmalısınız?',
      fastResponse: 'Hızlı Yanıt',
      fastResponseDesc: 'Tüm sorularınıza 24 saat içinde yanıt veriyoruz',
      expertTeam: 'Uzman Ekip',
      expertTeamDesc: 'Deneyimli seyahat danışmanlarımız size yardımcı olur',
      reliableService: 'Güvenilir Hizmet',
      reliableServiceDesc: 'Profesyonel ve güvenilir destek garantisi'
    }
  },
  en: {
    header: {
      home: 'Home',
      tours: 'Tours',
      destinations: 'Destinations',
      visa: 'Visa Support',
      blog: 'Blog',
      about: 'About Us',
      contact: 'Contact',
      bookNow: 'Book Now',
      announcement: 'Last Day for Early Booking Offers!',
      checkOffers: 'Check Offers →',
      lastMinuteDeals: '🎉 Last Minute Deals',
      viewDeals: 'View Deals',
      hours: 'Hours',
      minutes: 'Minutes',
      seconds: 'Seconds',
      search: 'Search',
      searchPlaceholder: 'Dubai, Bali, Thailand...'
    },
    hero: {
      title: 'Discover Your Next Adventure',
      subtitle: 'Explore the world\'s amazing destinations with our carefully selected tour packages and expert guides',
      destination: 'Destination',
      destinationPlaceholder: 'Where to?',
      date: 'Date',
      guests: 'Number of Guests',
      guest: 'Guest',
      search: 'Search',
      explorePackages: 'Explore Packages',
      contactUs: 'Contact Us'
    },
    home: {
      popularDestinations: 'Popular Destinations',
      popularDestinationsSubtitle: 'Discover the most preferred vacation spots',
      featuredPackages: 'Featured Packages',
      featuredPackagesSubtitle: 'Explore our specially curated tour packages',
      whyChooseUs: 'Why Choose Us?',
      whyChooseUsSubtitle: 'With 17 years of experience and a professional service approach, we are always by your side',
      bestPrices: 'Best Prices',
      bestPricesDesc: 'Quality vacation experience with the most competitive prices in the market',
      expertGuides: 'Expert Guides',
      expertGuidesDesc: 'Unforgettable tours with our experienced and local guides',
      support247: '24/7 Support',
      support247Desc: 'We are always with you, instant solutions to your problems',
      easyBooking: 'Easy Booking',
      easyBookingDesc: 'Book your dream vacation in just a few clicks',
      from: 'from',
      viewAllTours: 'View All Tours',
      rating: 'Rating',
      reviews: 'Review',
      days: 'Days',
      groupSize: 'Group Size',
      people: 'People',
      departure: 'Departure',
      everyday: 'Everyday',
      monThu: 'Mon, Thu',
      tueWedSat: 'Tue, Wed, Sat',
      worldwideCoverage: 'Worldwide Coverage',
      worldwideCoverageDesc: 'Explore 500+ destinations in 6 continents',
      safeSecure: 'Safe & Secure',
      safeSecureDesc: 'Your safety is our priority with 24/7 support',
      support247Title: '24/7 Support',
      support247TitleDesc: 'Get help anytime, anywhere with our dedicated team',
      bestPricesTitle: 'Best Prices',
      bestPricesTitleDesc: 'Competitive pricing without hidden fees'
    },
    tours: {
      international: 'International Tours',
      abroad: 'Abroad Tours',
      culture: 'Cultural Tours',
      turkey: 'Turkey Tours',
      visaFree: 'Visa-Free Destinations',
      montenegro: 'Montenegro',
      balkans: 'Balkan Tours',
      italy: 'Italy',
      dubai: 'Dubai',
      japan: 'Japan',
      egypt: 'Egypt',
      thailand: 'Thailand',
      bali: 'Bali (Indonesia)',
      greece: 'Greece',
      europeCulture: 'European Cultural Tours',
      asiaCulture: 'Asian Cultural Tours',
      middleEast: 'Middle East Tours',
      holyLands: 'Holy Lands',
      farEast: 'Far East',
      antalya: 'Antalya Tours',
      cappadocia: 'Cappadocia Tours',
      aegean: 'Aegean Tours',
      mediterranean: 'Mediterranean Tours'
    },
    destinations: {
      title: 'Popular Destinations',
      subtitle: 'Discover the most preferred vacation spots',
      tours: 'Tours',
      viewAll: 'View All Destinations'
    },
    packages: {
      title: 'Featured Packages',
      subtitle: 'Explore our specially curated tour packages',
      viewAll: 'View All Tours',
      from: 'from',
      perPerson: 'per person',
      viewDetails: 'View Details',
      days: 'Days',
      night: 'Night',
      nights: 'Nights'
    },
    features: {
      title: 'Why Choose Us?',
      bestPrices: 'Best Prices',
      bestPricesDesc: 'Quality vacation experience with the most competitive prices in the market',
      expertGuides: 'Expert Guides',
      expertGuidesDesc: 'Unforgettable tours with our experienced and local guides',
      support: '24/7 Support',
      supportDesc: 'We are always with you, instant solutions to your problems',
      easyBooking: 'Easy Booking',
      easyBookingDesc: 'Book your dream vacation in just a few clicks',
      flexiblePayment: 'Flexible Payment',
      flexiblePaymentDesc: 'Multiple payment options and installment plans available'
    },
    footer: {
      tagline: 'Your reliable partner for unforgettable travel experiences around the world.',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      destinations: 'Destinations',
      tourPackages: 'Tour Packages',
      visaSupport: 'Visa Support',
      contact: 'Contact',
      services: 'Our Services',
      hotelReservation: 'Hotel Reservation',
      flightTicket: 'Flight Ticket',
      tourGuides: 'Tour Guides',
      travelInsurance: 'Travel Insurance',
      copyright: 'All rights reserved.'
    },
    visa: {
      title: 'Visa Support Services',
      subtitle: 'We are with you in your visa process',
      description: 'We make your visa application process easier with our professional team.',
      visaConsultancy: 'Visa Consultancy',
      all: 'Visa Consultancy',
      dubai: 'Dubai Visa',
      subtitle2: 'Information about overseas visa applications. Simplify your visa procedures with our professional team.',
      applyNow: 'Apply Now',
      ourServices: 'Our Services',
      whyChooseUs: 'Why Choose Us?',
      documentPreparation: 'Document Preparation',
      documentPreparationDesc: 'We prepare all your visa application documents. We provide support for missing documents.',
      fastProcess: 'Fast Processing',
      fastProcessDesc: 'We complete and track your visa applications in the fastest way possible.',
      approvalGuarantee: 'Approval Guarantee',
      approvalGuaranteeDesc: 'We provide professional visa consultancy services with a high approval rate.',
      allCountries: 'All Countries',
      allCountriesDesc: 'We provide visa application support for any country in the world.',
      secureProcess: 'Secure Process',
      secureProcessDesc: 'Your documents are processed securely and your privacy is protected.',
      expertTeam: 'Expert Team',
      expertTeamDesc: 'Our experienced visa consultants are with you every step of the way.',
      passportServices: 'Passport Services',
      passportTitle: 'Getting a Passport',
      passportDesc: 'Passport applications must be made in person regardless of age. Since April 2, 2018, passport applications are made to Population Directorates.',
      passportDesc2: 'After paying the passport fee online or at banks and making an appointment online or by phone, it is sufficient to go to the population directorates with 2 biometric photos and your ID card.',
      passportRequirements: 'Required Documents for Passport',
      requirement1: '2 biometric photos',
      requirement2: 'ID card or population certificate',
      requirement3: 'Your old passport if available',
      requirement4: 'Student certificate (for those applying for free passport)',
      requirement5: 'Consent certificate for minors or restricted persons',
      simplifyProcess: 'Simplify Your Visa Process With Us',
      processDesc: 'With GNC Travel Visa Consultancy, you can make a complete application and minimize the risk of visa rejection by getting professional and quality visa consultancy service.',
      contactInfo: 'For visa information by country and to learn about the detailed visa application process, call +90 543 220 05 43 or send an email to info@gnctravel.com.',
      getFreeConsultation: 'Get Free Consultation',
      visaApplicationForm: 'Visa Application Form',
      formDesc: 'Fill out the form and our expert team will contact you as soon as possible.',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Your name and surname',
      emailPlaceholder: 'example@email.com',
      phone: 'Phone',
      phonePlaceholder: '+90 5XX XXX XX XX',
      destinationCountry: 'Destination Country',
      destinationCountryPlaceholder: 'e.g. United States',
      passportStatus: 'Passport Status',
      passportStatusPlaceholder: 'Select',
      havePassport: 'I Have a Passport',
      noPassport: 'I Don\'t Have a Passport',
      expiredPassport: 'I Have a Passport But It\'s Expired',
      yourMessage: 'Your Message',
      messagePlaceholder: 'If you would like to provide information about your visa application...',
      submitApplication: 'Submit Application',
      manyApplications: 'Many Visa Applications in Our Country',
      applicationsDesc: 'In our country, many visa applications are rejected due to incorrectly or incompletely filled forms, inappropriate document submission, and improper translation of documents.',
      professionalService: 'Professional Visa Consultancy',
      visaBlog: 'Visa Guide & Blog',
      blogDesc: 'Detailed information about visa application processes, required documents and expert tips',
      touristVisa: 'How to Get a Tourist Visa?',
      touristVisaDesc: 'Required documents, application process and important points for traveling abroad for tourist purposes.',
      readMore: 'Read More',
      studentVisa: 'Student Visa Application',
      studentVisaDesc: 'Application process, required documents and important details for student visa for studying abroad.',
      workVisa: 'Work Visa Application Guide',
      workVisaDesc: 'Work visa application, employer sponsorship and required documents for working abroad.',
      viewAllBlogPosts: 'View All Blog Posts',
      processInfo: 'Yurtdışı vize başvuru işlemlerinizi başvurudan ülkeye göre birçok farklılık göstermektedir. Profesyonel ekibimizle size en uygun çözümü sunuyoruz.',
      dubaiVisa: {
        title: 'Dubai Visa Services',
        subtitle: 'We simplify your visa process for Dubai travel',
        heroDesc: 'Professional visa consultancy service for your travel to the United Arab Emirates',
        whyDubai: 'Why Dubai?',
        whyDubaiDesc: 'Dubai is one of the world\'s most popular tourist destinations with luxury shopping malls, modern architecture, vibrant nightlife and family-friendly entertainment centers.',
        visaTypes: 'Dubai Visa Types',
        touristVisa: 'Tourist Visa',
        touristVisaDesc: 'Discover all the beauty of Dubai with a 30 or 90-day tourist visa',
        transitVisa: 'Transit Visa',
        transitVisaDesc: 'Transit visa for stays up to 96 hours in Dubai',
        multipleEntry: 'Multiple Entry Visa',
        multipleEntryDesc: 'Visa that allows multiple entries within 90 days',
        requirements: 'Required Documents',
        requirement1: 'Passport valid for at least 6 months',
        requirement2: 'Passport-size color photograph',
        requirement3: 'Hotel reservation document',
        requirement4: 'Flight ticket reservation',
        requirement5: 'Health insurance',
        requirement6: 'Bank statement',
        processTitle: 'Visa Application Process',
        processStep1: '1. Application Form',
        processStep1Desc: 'Fill out your online form',
        processStep2: '2. Document Check',
        processStep2Desc: 'Let us check your documents',
        processStep3: '3. Application',
        processStep3Desc: 'We make your application',
        processStep4: '4. Approval',
        processStep4Desc: 'Receive your visa',
        pricing: 'Pricing',
        from: 'from',
        applyNow: 'Apply Now',
        recommendedTours: 'Recommended Dubai Tours',
        viewAllDubaiTours: 'View All Dubai Tours',
        faq: 'Frequently Asked Questions',
        faqQ1: 'How long does it take to get a Dubai visa?',
        faqA1: 'Usually the visa approval is received within 3-5 business days.',
        faqQ2: 'How much does a Dubai visa cost?',
        faqA2: 'Visa fees vary depending on the visa type. Please contact us for detailed information.',
        faqQ3: 'How long does the Dubai visa process take?',
        faqA3: 'We recommend you allow an average of 1 week for the application process to be completed.',
        faqQ4: 'How long must my passport be valid for a Dubai visa?',
        faqA4: 'Your passport must be valid for at least 6 months.',
        contactForVisa: 'Contact Us for Visa Consultancy',
        contactDesc: 'Our expert team is ready to help you with your Dubai visa process'
      }
    },
    about: {
      title: 'About Us',
      subtitle: 'We are with you with 17 years of experience',
      whoWeAre: 'Who We Are',
      whoWeAreDesc: 'GNC Travel Agency has been serving in the tourism industry for 17 years. We offer the best vacation experience to our customers with our expert team and quality service approach.',
      ourMission: 'Our Mission',
      ourMissionDesc: 'To provide unforgettable travel experiences and make dreams come true.',
      ourVision: 'Our Vision',
      ourVisionDesc: 'To be the most trusted travel agency in Turkey and around the world.',
      whyUs: 'Why Choose Us?',
      experience: '17 Years of Experience',
      experienceDesc: 'Professional service with industry knowledge and experience',
      satisfaction: 'Customer Satisfaction',
      satisfactionDesc: 'We prioritize customer happiness and work for you',
      destinations: '100+ Destinations',
      destinationsDesc: 'Wide range of tours to various countries around the world',
      team: 'Expert Team',
      teamDesc: 'Expert guides and consultants at your service'
    },
    contact: {
      title: 'Contact',
      subtitle: 'How can we help you?',
      getInTouch: 'Get In Touch',
      getInTouchDesc: 'Contact us for your questions, suggestions or support requests. Our team is here to help you.',
      address: 'Address',
      addressText: 'Side Mah. Yavuz Sultan Selim Blv. No:6 A-Z01 MANAVGAT / ANTALYA',
      phone: 'Phone',
      email: 'Email',
      workingHours: 'Working Hours',
      workingHoursText: 'Monday – Saturday: 09:00 – 19:00',
      sundayClosed: 'Closed on Sundays',
      sendMessage: 'Send Message',
      name: 'Your Name',
      namePlaceholder: 'Enter your name',
      emailPlaceholder: 'Your email address',
      phonePlaceholder: 'Your phone number',
      subject: 'Subject',
      subjectPlaceholder: 'Select subject',
      general: 'General Information',
      tourInquiry: 'Tour Inquiry',
      visaSupport: 'Visa Support',
      complaint: 'Complaint/Suggestion',
      message: 'Your Message',
      messagePlaceholder: 'Write your message here...',
      send: 'Send Message',
      sending: 'Sending...',
      successMessage: 'Thank you! Your message has been received. We will get back to you as soon as possible.',
      mapTitle: 'Our Location',
      whyContact: 'Why Contact Us?',
      fastResponse: 'Fast Response',
      fastResponseDesc: 'We respond to all your questions within 24 hours',
      expertTeam: 'Expert Team',
      expertTeamDesc: 'Our experienced travel consultants will help you',
      reliableService: 'Reliable Service',
      reliableServiceDesc: 'Professional and reliable support guarantee'
    },
    blog: {
      title: 'Visa Guide & Blog',
      subtitle: 'Everything you need to know about overseas visa applications. Tips and detailed guides from our expert team.',
      applyForVisa: 'Apply for Visa',
      getExpertSupport: 'Get Expert Support',
      category: 'Category',
      author: 'Author',
      readingTime: 'min read',
      continueReading: 'Continue Reading',
      needHelp: 'Need Help with Your Visa Application?',
      needHelpDesc: 'As GNC Travel, we provide you with professional support in your visa application process. Our expert team checks all your documents and follows the application process.',
      callUs: 'Call Us'
    },
    tourDetails: {
      overview: 'Overview',
      itinerary: 'Itinerary',
      included: 'What\'s Included',
      excluded: 'What\'s Not Included',
      importantInfo: 'Important Information',
      bookNow: 'Book Now',
      from: 'from',
      perPerson: 'per person',
      duration: 'Duration',
      days: 'Days',
      nights: 'Nights',
      groupSize: 'Group Size',
      people: 'People',
      language: 'Tour Language',
      turkish: 'Turkish',
      english: 'English',
      german: 'German',
      day: 'Day',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      hotel: 'Hotel Accommodation',
      transportation: 'Transportation',
      guide: 'Professional Guide',
      entrance: 'Entrance Fees',
      meals: 'Meals',
      insurance: 'Travel Insurance',
      flights: 'International Flights',
      personalExpenses: 'Personal Expenses',
      tips: 'Tips',
      optional: 'Optional Tours',
      passport: 'Valid Passport Required',
      visa: 'Visa May Be Required',
      cancellation: 'Cancellation Policy Applies',
      similar: 'Similar Tours',
      viewDetails: 'View Details'
    },
    common: {
      loading: 'Loading...',
      error: 'An error occurred',
      success: 'Successful',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      search: 'Search',
      filter: 'Filter',
      sortBy: 'Sort By',
      showMore: 'Show More',
      showLess: 'Show Less',
      backToHome: 'Back to Home',
      notFound: 'Page Not Found',
      notFoundDesc: 'The page you are looking for does not exist.',
      serverError: 'Server Error',
      serverErrorDesc: 'Something went wrong. Please try again later.'
    }
  },
  de: {
    header: {
      home: 'Startseite',
      tours: 'Touren',
      destinations: 'Reiseziele',
      visa: 'Visum-Unterstützung',
      blog: 'Blog',
      about: 'Über Uns',
      contact: 'Kontakt',
      bookNow: 'Jetzt Buchen',
      announcement: 'Letzter Tag für Frühbuchungsangebote!',
      checkOffers: 'Angebote Prüfen →',
      lastMinuteDeals: '🎉 Letzte-Minute-Angebote',
      viewDeals: 'Angebote Ansehen',
      hours: 'Stunden',
      minutes: 'Minuten',
      seconds: 'Sekunden',
      search: 'Suchen',
      searchPlaceholder: 'Dubai, Bali, Thailand...'
    },
    hero: {
      title: 'Entdecken Sie Ihren nächsten Abenteuer',
      subtitle: 'Erkunden Sie die Welt mit unseren sorgfältig ausgewählten Tourpaketen und erfahrenen Guides',
      destination: 'Zielort',
      destinationPlaceholder: 'Wohin?',
      date: 'Datum',
      guests: 'Anzahl der Gäste',
      guest: 'Gast',
      search: 'Suchen',
      explorePackages: 'Pakete Erkunden',
      contactUs: 'Kontaktieren Sie Uns'
    },
    home: {
      popularDestinations: 'Beliebte Reiseziele',
      popularDestinationsSubtitle: 'Entdecken Sie die beliebtesten Urlaubsorte',
      featuredPackages: 'Empfohlene Pakete',
      featuredPackagesSubtitle: 'Entdecken Sie unsere speziell kuratierten Tourpakete',
      whyChooseUs: 'Warum Uns Wählen?',
      whyChooseUsSubtitle: 'Mit 17 Jahren Erfahrung und einem professionellen Service-Ansatz sind wir immer an Ihrer Seite',
      bestPrices: 'Beste Preise',
      bestPricesDesc: 'Qualitatives Urlaubserlebnis zu den wettbewerbsfähigsten Preisen',
      expertGuides: 'Experten-Guides',
      expertGuidesDesc: 'Unvergessliche Touren mit unseren erfahrenen und lokalen Guides',
      support247: '24/7 Support',
      support247Desc: 'Wir sind immer für Sie da, sofortige Lösungen für Ihre Probleme',
      easyBooking: 'Einfache Buchung',
      easyBookingDesc: 'Buchen Sie Ihren Traumurlaub in nur wenigen Klicks',
      from: 'ab',
      viewAllTours: 'Alle Touren Ansehen',
      rating: 'Bewertung',
      reviews: 'Bewertung',
      days: 'Tage',
      groupSize: 'Gruppengröße',
      people: 'Personen',
      departure: 'Abreise',
      everyday: 'Jeden Tag',
      monThu: 'Mo, Do',
      tueWedSat: 'Di, Mi, Sa',
      worldwideCoverage: 'Weltweite Abdeckung',
      worldwideCoverageDesc: '500+ Reiseziele in 6 Kontinenten erkunden',
      safeSecure: 'Sicher & Sicherheit',
      safeSecureDesc: 'Ihre Sicherheit ist unsere Priorität mit 24/7-Support',
      support247Title: '24/7-Support',
      support247TitleDesc: 'Holen Sie sich Hilfe jederzeit und an jedem Ort mit unserem dedizierten Team',
      bestPricesTitle: 'Beste Preise',
      bestPricesTitleDesc: 'Wettbewerbsfähige Preise ohne verborgene Gebühren'
    },
    tours: {
      international: 'Internationale Touren',
      abroad: 'Auslandstouren',
      culture: 'Kulturreisen',
      turkey: 'Türkei Touren',
      visaFree: 'Visumfreie Reiseziele',
      montenegro: 'Montenegro',
      balkans: 'Balkan Touren',
      italy: 'Italien',
      dubai: 'Dubai',
      japan: 'Japan',
      egypt: 'Ägypten',
      thailand: 'Thailand',
      bali: 'Bali (Indonesien)',
      greece: 'Griechenland',
      europeCulture: 'Europäische Kulturreisen',
      asiaCulture: 'Asiatische Kulturreisen',
      middleEast: 'Naher Osten Touren',
      holyLands: 'Heilige Länder',
      farEast: 'Ferner Osten',
      antalya: 'Antalya Touren',
      cappadocia: 'Kappadokien Touren',
      aegean: 'Ägäis Touren',
      mediterranean: 'Mittelmeer Touren'
    },
    destinations: {
      title: 'Beliebte Reiseziele',
      subtitle: 'Entdecken Sie die beliebtesten Urlaubsorte',
      tours: 'Tour'
    },
    packages: {
      title: 'Empfohlene Pakete',
      subtitle: 'Entdecken Sie unsere speziell kuratierten Tourpakete',
      viewAll: 'Alle Touren Ansehen',
      from: 'ab',
      perPerson: 'pro Person',
      viewDetails: 'Details Ansehen',
      days: 'Tage'
    },
    features: {
      title: 'Warum Uns Wählen?',
      bestPrices: 'Beste Preise',
      bestPricesDesc: 'Qualitatives Urlaubserlebnis zu den wettbewerbsfähigsten Preisen',
      expertGuides: 'Experten-Guides',
      expertGuidesDesc: 'Unvergessliche Touren mit unseren erfahrenen und lokalen Guides',
      support: '24/7 Support',
      supportDesc: 'Wir sind immer für Sie da, sofortige Lösungen für Ihre Probleme'
    },
    footer: {
      tagline: 'Ihr vertrauenswürdiger Partner für unvergessliche Reiseerlebnisse auf der ganzen Welt.',
      quickLinks: 'Schnelllinks',
      aboutUs: 'Über Uns',
      destinations: 'Reiseziele',
      tourPackages: 'Tourpakete',
      visaSupport: 'Visum-Unterstützung',
      contact: 'Kontakt',
      services: 'Unsere Dienstleistungen',
      hotelReservation: 'Hotelbuchung',
      flightTicket: 'Fluggesellschaft',
      tourGuides: 'Tourleiter',
      travelInsurance: 'Reiseversicherung',
      copyright: 'Alle Rechte vorbehalten.'
    },
    visa: {
      title: 'Visum-Support-Services',
      subtitle: 'Wir begleiten Sie bei Ihrem Visumsprozess',
      description: 'Mit unserem professionellen Team erleichtern wir Ihren Visumsantragsprozess.',
      visaConsultancy: 'Visum-Dienstleistung',
      all: 'Visum-Dienstleistung',
      dubai: 'Dubai-Visum',
      subtitle2: 'Informationen zu Auslandsvisumanträgen. Vereinfachen Sie Ihre Visumanträge mit unserem professionellen Team.',
      applyNow: 'Jetzt anwenden',
      ourServices: 'Unsere Dienstleistungen',
      whyChooseUs: 'Warum uns wählen?',
      documentPreparation: 'Dokumentenbereitung',
      documentPreparationDesc: 'Wir bereiten alle Ihre Visumantragsdokumente vor. Wir unterstützen Sie bei fehlenden Dokumenten.',
      fastProcess: 'Schnelle Bearbeitung',
      fastProcessDesc: 'Wir bearbeiten und verfolgen Ihre Visumanträge in der schnellstmöglichen Weise.',
      approvalGuarantee: 'Genehmigungsgarantie',
      approvalGuaranteeDesc: 'Wir bieten professionelle Visum-Dienstleistungen mit einem hohen Genehmigungsrate.',
      allCountries: 'Alle Länder',
      allCountriesDesc: 'Wir bieten Visumantragsunterstützung für jedes Land der Welt.',
      secureProcess: 'Sicherer Prozess',
      secureProcessDesc: 'Ihre Dokumente werden sicher verarbeitet und Ihre Privatsphäre geschützt.',
      expertTeam: 'Experte Team',
      expertTeamDesc: 'Unsere erfahrenen Visumantragsberater begleiten Sie jeden Schritt des Weges.',
      passportServices: 'Passdienstleistungen',
      passportTitle: 'Pass beantragen',
      passportDesc: 'Passanträge müssen unabhängig von Alter persönlich gestellt werden. Seit dem 2. April 2018 werden Passanträge bei Bevölkerungsämtern gestellt.',
      passportDesc2: 'Nach dem Online-Zahlen oder Bezahlen des Passgebührens in einer Bank und dem Online- oder telefonischen Terminbuchung ist es ausreichend, mit 2 biometrischen Fotos und Ihrer ID-Karte bei den Bevölkerungsämtern aufzutreten.',
      passportRequirements: 'Erforderliche Dokumente für Pass',
      requirement1: '2 biometrische Fotos',
      requirement2: 'ID-Karte oder Bevölkerungsnachweis',
      requirement3: 'Ihr alter Pass, falls vorhanden',
      requirement4: 'Studentenbescheinigung (für diejenigen, die ein kostenloses Pass beantragen)',
      requirement5: 'Einwilligungsnachweis für Minderjährige oder eingeschränkte Personen',
      simplifyProcess: 'Vereinfachen Sie Ihren Visumsprozess mit uns',
      processDesc: 'Mit GNC Travel Visum-Dienstleistung können Sie eine vollständige Anmeldung erstellen und das Risiko einer Ablehnung des Visums durch den Einsatz professioneller und qualitativ hochwertiger Visum-Dienstleistungen minimieren.',
      contactInfo: 'Für Informationen zu Visumanträgen nach Land und um detaillierte Informationen zum Visumantragsprozess rufen Sie uns unter +90 543 220 05 43 an oder senden Sie eine E-Mail an info@gnctravel.com.',
      getFreeConsultation: 'Kostenlose Beratung erhalten',
      visaApplicationForm: 'Visumantragsformular',
      formDesc: 'Füllen Sie das Formular aus und unser Expertenteam wird Sie so schnell wie möglich kontaktieren.',
      fullName: 'Vollständiger Name',
      fullNamePlaceholder: 'Ihr Vor- und Nachname',
      emailPlaceholder: 'beispiel@email.com',
      phone: 'Telefon',
      phonePlaceholder: '+90 5XX XXX XX XX',
      destinationCountry: 'Zielland',
      destinationCountryPlaceholder: 'z.B. Vereinigte Staaten',
      passportStatus: 'Passstatus',
      passportStatusPlaceholder: 'Wählen',
      havePassport: 'Ich habe ein Pass',
      noPassport: 'Ich habe kein Pass',
      expiredPassport: 'Ich habe ein Pass, aber es ist abgelaufen',
      yourMessage: 'Ihre Nachricht',
      messagePlaceholder: 'Wenn Sie Informationen zu Ihrem Visumantrag bereitstellen möchten...',
      submitApplication: 'Antrag einreichen',
      submitSuccess: 'Ihr Antrag wurde erhalten! Wir werden uns so schnell wie möglich bei Ihnen melden.',
      manyApplications: 'Viele Visumanträge in unserem Land',
      applicationsDesc: 'In unserem Land werden viele Visumanträge abgelehnt, da Formulare falsch oder unvollständig ausgefüllt sind, Dokumente unangemessen eingereicht werden oder Dokumente nicht korrekt übersetzt werden.',
      professionalService: 'Professionelle Visum-Dienstleistung',
      visaBlog: 'Visum-Leitfaden & Blog',
      blogDesc: 'Detaillierte Informationen zu Visumantragsprozessen, erforderlichen Dokumenten und Expertentipps',
      touristVisa: 'Wie erhält man ein Touristenvisum?',
      touristVisaDesc: 'Erforderliche Dokumente, Antragsprozess und wichtige Punkte für Reisen ins Ausland zu Touristenzwecken.',
      readMore: 'Mehr lesen',
      studentVisa: 'Studentenvisumantrag',
      studentVisaDesc: 'Antragsprozess, erforderliche Dokumente und wichtige Details für ein Studentenvisum zum Studium im Ausland.',
      workVisa: 'Leitfaden für die Antragstellung eines Arbeitervisums',
      workVisaDesc: 'Antragstellung eines Arbeitervisums, Arbeitgeber-Sponsoring und erforderliche Dokumente für die Arbeit im Ausland.',
      viewAllBlogPosts: 'Alle Blog-Beiträge anzeigen',
      processInfo: 'Yurtdışı vize başvuru işlemlerinizi başvurudan ülkeye göre birçok farklılık göstermektedir. Profesyonel ekibimizle size en uygun çözümü sunuyoruz.',
      dubaiVisa: {
        title: 'Dubai Visa Services',
        subtitle: 'We simplify your visa process for Dubai travel',
        heroDesc: 'Professional visa consultancy service for your travel to the United Arab Emirates',
        whyDubai: 'Why Dubai?',
        whyDubaiDesc: 'Dubai is one of the world\'s most popular tourist destinations with luxury shopping malls, modern architecture, vibrant nightlife and family-friendly entertainment centers.',
        visaTypes: 'Dubai Visa Types',
        touristVisa: 'Tourist Visa',
        touristVisaDesc: 'Discover all the beauty of Dubai with a 30 or 90-day tourist visa',
        transitVisa: 'Transit Visa',
        transitVisaDesc: 'Transit visa for stays up to 96 hours in Dubai',
        multipleEntry: 'Multiple Entry Visa',
        multipleEntryDesc: 'Visa that allows multiple entries within 90 days',
        requirements: 'Required Documents',
        requirement1: 'Passport valid for at least 6 months',
        requirement2: 'Passport-size color photograph',
        requirement3: 'Hotel reservation document',
        requirement4: 'Flight ticket reservation',
        requirement5: 'Health insurance',
        requirement6: 'Bank statement',
        processTitle: 'Visa Application Process',
        processStep1: '1. Application Form',
        processStep1Desc: 'Fill out your online form',
        processStep2: '2. Document Check',
        processStep2Desc: 'Let us check your documents',
        processStep3: '3. Application',
        processStep3Desc: 'We make your application',
        processStep4: '4. Approval',
        processStep4Desc: 'Receive your visa',
        pricing: 'Pricing',
        from: 'from',
        applyNow: 'Apply Now',
        recommendedTours: 'Recommended Dubai Tours',
        viewAllDubaiTours: 'View All Dubai Tours',
        faq: 'Frequently Asked Questions',
        faqQ1: 'How long does it take to get a Dubai visa?',
        faqA1: 'Usually the visa approval is received within 3-5 business days.',
        faqQ2: 'How much does a Dubai visa cost?',
        faqA2: 'Visa fees vary depending on the visa type. Please contact us for detailed information.',
        faqQ3: 'How long does the Dubai visa process take?',
        faqA3: 'We recommend you allow an average of 1 week for the application process to be completed.',
        faqQ4: 'How long must my passport be valid for a Dubai visa?',
        faqA4: 'Your passport must be valid for at least 6 months.',
        contactForVisa: 'Contact Us for Visa Consultancy',
        contactDesc: 'Our expert team is ready to help you with your Dubai visa process'
      }
    },
    about: {
      title: 'Über Uns',
      subtitle: 'Wir sind mit 17 Jahren Erfahrung an Ihrer Seite'
    },
    contact: {
      title: 'Kontakt',
      subtitle: 'Wie können wir Ihnen helfen?',
      getInTouch: 'Get In Touch',
      getInTouchDesc: 'Contact us for your questions, suggestions or support requests. Our team is here to help you.',
      address: 'Address',
      addressText: 'Side Mah. Yavuz Sultan Selim Blv. No:6 A-Z01 MANAVGAT / ANTALYA',
      phone: 'Phone',
      email: 'Email',
      workingHours: 'Working Hours',
      workingHoursText: 'Monday – Saturday: 09:00 – 19:00',
      sundayClosed: 'Closed on Sundays',
      sendMessage: 'Send Message',
      name: 'Your Name',
      namePlaceholder: 'Enter your name',
      emailPlaceholder: 'Your email address',
      phonePlaceholder: 'Your phone number',
      subject: 'Subject',
      subjectPlaceholder: 'Select subject',
      general: 'General Information',
      tourInquiry: 'Tour Inquiry',
      visaSupport: 'Visa Support',
      complaint: 'Complaint/Suggestion',
      message: 'Your Message',
      messagePlaceholder: 'Write your message here...',
      send: 'Send Message',
      sending: 'Sending...',
      successMessage: 'Thank you! Your message has been received. We will get back to you as soon as possible.',
      mapTitle: 'Our Location',
      whyContact: 'Why Contact Us?',
      fastResponse: 'Fast Response',
      fastResponseDesc: 'We respond to all your questions within 24 hours',
      expertTeam: 'Expert Team',
      expertTeamDesc: 'Our experienced travel consultants will help you',
      reliableService: 'Reliable Service',
      reliableServiceDesc: 'Professional and reliable support guarantee'
    }
  }
};